@extend('master')
@section('content')

<div id="content" class="">
            <div class="container container-main">
               
        <a href="/course/393971/3000-tu-vung-tieng-anh-thong-dung-oxford-wordlist/2/?action=next"
           class="level-nav level-nav-next"
           accesskey="c"
           title="Cấp độ tiếp theo [Phím tắt: C]"
           data-placement="top">
            <span class="level-name">Cấp độ 2</span>
            <i class="ico ico-left ico-arr-right"></i>
        </a>
    

    <div class="central-column">

<div class="progress-box progress-box-level with-icon">
    
    <div class="level-icon">
        <strong class="level-number">
            
                Cấp độ 1
            
        </strong>
        
        <i class="level-ico level-ico-plant-inactive"></i>
    
    </div>
    
    <div class="infos">
               
            <h3 class="progress-box-title">
                100
            </h3>
        
        <div class="progress"
             >
            
        </div>
    </div>

    <hr>

    <div class="actions actions-left">
        
    </div>
    <div class="actions actions-right">
        
    <a href="/join/?skip_onboarding=/course/393971/3000-tu-vung-tieng-anh-thong-dung-oxford-wordlist/1/garden/learn/"
       tabindex="1"
       data-tracking-name="course_mode"
       class="button green">
        Học những từ này
    </a>

    </div>

    <div class="clear"></div>
</div>

                <h4>
                    100
                    từ

                    <span class="pull-right">
                        
                            0 bỏ qua
                        
                    </span>
                </h4>
            
<div class="things clearfix" data-column-a="1" data-column-b="2"><div class="things-header things-row"><i class="ico ico-seed ico-purple"></i> Học
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <i class="ico ico-water ico-blue"></i> Ôn tập
    </div><div class="ignore-ui things-row clearfix"><h2>Bỏ qua từ</h2><p>
            Chọn các ô dưới đây để bỏ qua / giữ lại từ, rồi chọn nút Lưu phía dưới. Những từ bị bỏ qua sẽ không xuất hiện trong tiết học nào nữa.
        </p><p class="align-right"><a href="#" class="ignore-all btn btn-small">
                Chọn hết
            </a><a href="#" class="ignore-none btn btn-small">
                Bỏ chọn
            </a></p></div><div class="ignore-ui things-row" style="text-align: right"><strong>Bỏ qua?</strong></div><div class="thing text-text"
            data-learnable-id="2586117079298" data-thing-id="39461015"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">abandon</div></div><div class="col_b col text"><div class="text">(v) bỏ, từ bỏ</div></div></div><div class="thing text-text"
            data-learnable-id="2586117931266" data-thing-id="39461028"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">abandoned</div></div><div class="col_b col text"><div class="text">(adj) bị bỏ rơi, bị ruồng bỏ</div></div></div><div class="thing text-text"
            data-learnable-id="2586125009154" data-thing-id="39461136"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">ability</div></div><div class="col_b col text"><div class="text">(n) khả năng, năng lực</div></div></div><div class="thing text-text"
            data-learnable-id="2586128744706" data-thing-id="39461193"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">able</div></div><div class="col_b col text"><div class="text">(adj) có năng lực, có tài</div></div></div><div class="thing text-text"
            data-learnable-id="2586140737794" data-thing-id="39461376"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">unable</div></div><div class="col_b col text"><div class="text">(adj)  không có năng lực, không có tài</div></div></div><div class="thing text-text"
            data-learnable-id="2586141917442" data-thing-id="39461394"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">about</div></div><div class="col_b col text"><div class="text">(adv) (prep) khoảng, về</div></div></div><div class="thing text-text"
            data-learnable-id="2586143490306" data-thing-id="39461418"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">abroad</div></div><div class="col_b col text"><div class="text">(adv)  ở, ra nước ngoài, ngoài trời</div></div></div><div class="thing text-text"
            data-learnable-id="2586157842690" data-thing-id="39461637"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">absence</div></div><div class="col_b col text"><div class="text">(n) sự vắng mặt</div></div></div><div class="thing text-text"
            data-learnable-id="2586164658434" data-thing-id="39461741"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">absent</div></div><div class="col_b col text"><div class="text">(adj) vắng mặt, nghỉ</div></div></div><div class="thing text-text"
            data-learnable-id="2586166231298" data-thing-id="39461765"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">absolute</div></div><div class="col_b col text"><div class="text">(adj) tuyệt đối, hoàn toàn</div></div></div><div class="thing text-text"
            data-learnable-id="2586168000770" data-thing-id="39461792"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">absolutely</div></div><div class="col_b col text"><div class="text">(adv)  tuyệt đối, hoàn toàn</div></div></div><div class="thing text-text"
            data-learnable-id="2586169639170" data-thing-id="39461817"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">absorb</div></div><div class="col_b col text"><div class="text">(v) thu hút, hấp thu, lôi cuốn</div></div></div><div class="thing text-text"
            data-learnable-id="2586171212034" data-thing-id="39461841"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">abuse</div></div><div class="col_b col text"><div class="text">(n) (v)  lộng hành, lạm dụng</div></div></div><div class="thing text-text"
            data-learnable-id="2586173505794" data-thing-id="39461876"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">academic</div></div><div class="col_b col text"><div class="text">(adj) thuộc học viện, ĐH, viện hàn lâm</div></div></div><div class="thing text-text"
            data-learnable-id="2586181959938" data-thing-id="39462005"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accent</div></div><div class="col_b col text"><div class="text">(n)  trọng âm, dấu trọng âm</div></div></div><div class="thing text-text"
            data-learnable-id="2586183860482" data-thing-id="39462034"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accept</div></div><div class="col_b col text"><div class="text">(v) chấp nhận, chấp thuận</div></div></div><div class="thing text-text"
            data-learnable-id="2586247889154" data-thing-id="39463011"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">acceptable</div></div><div class="col_b col text"><div class="text">(adj) có thể chấp nhận, chấp thuận</div></div></div><div class="thing text-text"
            data-learnable-id="2586254115074" data-thing-id="39463106"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">unacceptable</div></div><div class="col_b col text"><div class="text">(adj) không thể chấp nhận,không tán thành, không thể tha thứ</div></div></div><div class="thing text-text"
            data-learnable-id="2586257457410" data-thing-id="39463157"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">access</div></div><div class="col_b col text"><div class="text">(n) lối, cửa, đường vào</div></div></div><div class="thing text-text"
            data-learnable-id="2586258702594" data-thing-id="39463176"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accident</div></div><div class="col_b col text"><div class="text">(n) tai nạn, rủi ro</div></div></div><div class="thing text-text"
            data-learnable-id="2586261651714" data-thing-id="39463221"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accidental</div></div><div class="col_b col text"><div class="text">(adj) tình cờ, bất ngờ</div></div></div><div class="thing text-text"
            data-learnable-id="2586262896898" data-thing-id="39463240"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accidentally</div></div><div class="col_b col text"><div class="text">(adv) tình cờ, ngẫu nhiên</div></div></div><div class="thing text-text"
            data-learnable-id="2586264666370" data-thing-id="39463267"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accommodation</div></div><div class="col_b col text"><div class="text">(n) sự thích nghi, điều tiết</div></div></div><div class="thing text-text"
            data-learnable-id="2586266829058" data-thing-id="39463300"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accompany</div></div><div class="col_b col text"><div class="text">(v) đi theo, đi cùng, kèm theo</div></div></div><div class="thing text-text"
            data-learnable-id="2586268991746" data-thing-id="39463333"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">according to</div></div><div class="col_b col text"><div class="text">(prep)  theo, y theo</div></div></div><div class="thing text-text"
            data-learnable-id="2586272268546" data-thing-id="39463383"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">account</div></div><div class="col_b col text"><div class="text">(n) (v) tài khoản, kế toán; tính toán, tính đến</div></div></div><div class="thing text-text"
            data-learnable-id="2586273579266" data-thing-id="39463403"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accurate</div></div><div class="col_b col text"><div class="text">(adj) đúng đắn, chính xác, xác đáng</div></div></div><div class="thing text-text"
            data-learnable-id="2586276331778" data-thing-id="39463445"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accurately</div></div><div class="col_b col text"><div class="text">(adv) đúng đắn, chính xác</div></div></div><div class="thing text-text"
            data-learnable-id="2586277839106" data-thing-id="39463468"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">accuse</div></div><div class="col_b col text"><div class="text">(v) tố cáo, buộc tội, kết tội</div></div></div><div class="thing text-text"
            data-learnable-id="2586279805186" data-thing-id="39463498"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">achieve</div></div><div class="col_b col text"><div class="text">(v) đạt được, dành được</div></div></div><div class="thing text-text"
            data-learnable-id="2586281443586" data-thing-id="39463523"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">achievement</div></div><div class="col_b col text"><div class="text">(n) thành tích, thành tựu</div></div></div><div class="thing text-text"
            data-learnable-id="2586282688770" data-thing-id="39463542"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">acid</div></div><div class="col_b col text"><div class="text">(n) axit</div></div></div><div class="thing text-text"
            data-learnable-id="2586284851458" data-thing-id="39463575"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">acknowledge</div></div><div class="col_b col text"><div class="text">(v) công nhận, thừa nhận</div></div></div><div class="thing text-text"
            data-learnable-id="2586286555394" data-thing-id="39463601"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">acquire</div></div><div class="col_b col text"><div class="text">(v) dành được, đạt được, kiếm được</div></div></div><div class="thing text-text"
            data-learnable-id="2586288193794" data-thing-id="39463626"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">across</div></div><div class="col_b col text"><div class="text">(adv) (prep) qua, ngang qua</div></div></div><div class="thing text-text"
            data-learnable-id="2586289438978" data-thing-id="39463645"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">act</div></div><div class="col_b col text"><div class="text">(n) (v) hành động, hành vi, cử chỉ, đối xử</div></div></div><div class="thing text-text"
            data-learnable-id="2586290749698" data-thing-id="39463665"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">action</div></div><div class="col_b col text"><div class="text">(n) hành động, hành vi, tác động</div></div></div><div class="thing text-text"
            data-learnable-id="2586291863810" data-thing-id="39463682"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">take action</div></div><div class="col_b col text"><div class="text">hành động</div></div></div><div class="thing text-text"
            data-learnable-id="2586613973250" data-thing-id="39468597"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">actively</div></div><div class="col_b col text"><div class="text">(adv) tích cực,hăng hái, nhanh nhẹn, linh lợi</div></div></div><div class="thing text-text"
            data-learnable-id="2586616463618" data-thing-id="39468635"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">activity</div></div><div class="col_b col text"><div class="text">(n) sự tích cực, sự hoạt động, sự hăng hái, sự linh lợi</div></div></div><div class="thing text-text"
            data-learnable-id="2586620395778" data-thing-id="39468695"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">actor</div></div><div class="col_b col text"><div class="text">(n) diễn viên nam</div></div></div><div class="thing text-text"
            data-learnable-id="2586622099714" data-thing-id="39468721"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">actress</div></div><div class="col_b col text"><div class="text">(n) diễn viên nữ</div></div></div><div class="thing text-text"
            data-learnable-id="2586634617090" data-thing-id="39468912"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">actual</div></div><div class="col_b col text"><div class="text">(adj) thực tế, có thật</div></div></div><div class="thing text-text"
            data-learnable-id="2586637893890" data-thing-id="39468962"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">actually</div></div><div class="col_b col text"><div class="text">(adv) hiện nay, hiện tại</div></div></div><div class="thing text-text"
            data-learnable-id="2586639991042" data-thing-id="39468994"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adapt</div></div><div class="col_b col text"><div class="text">(v) tra, lắp vào</div></div></div><div class="thing text-text"
            data-learnable-id="2586640974082" data-thing-id="39469009"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">add</div></div><div class="col_b col text"><div class="text">(v) cộng, thêm vào</div></div></div><div class="thing text-text"
            data-learnable-id="2586643661058" data-thing-id="39469050"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">addition</div></div><div class="col_b col text"><div class="text">(n) tính cộng, phép cộng</div></div></div><div class="thing text-text"
            data-learnable-id="2586644775170" data-thing-id="39469067"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">in addition (to)</div></div><div class="col_b col text"><div class="text">thêm vào</div></div></div><div class="thing text-text"
            data-learnable-id="2586648248578" data-thing-id="39469120"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">additional</div></div><div class="col_b col text"><div class="text">(adj) thêm vào, tăng thêm</div></div></div><div class="thing text-text"
            data-learnable-id="2586649624834" data-thing-id="39469141"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">address</div></div><div class="col_b col text"><div class="text">(n) (v) địa chỉ, đề địa chỉ</div></div></div><div class="thing text-text"
            data-learnable-id="2586650870018" data-thing-id="39469160"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adequate</div></div><div class="col_b col text"><div class="text">(adj) đầy, đầy đủ</div></div></div><div class="thing text-text"
            data-learnable-id="2586651525378" data-thing-id="39469170"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adequately</div></div><div class="col_b col text"><div class="text">(adv) tương xứng, thỏa đáng</div></div></div><div class="thing text-text"
            data-learnable-id="2586652442882" data-thing-id="39469184"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adjust</div></div><div class="col_b col text"><div class="text">(v) sửa lại cho đúng, điều chỉnh</div></div></div><div class="thing text-text"
            data-learnable-id="2586653360386" data-thing-id="39469198"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">admiration</div></div><div class="col_b col text"><div class="text">(n) sự khâm phục,người khâm phục, thán phục</div></div></div><div class="thing text-text"
            data-learnable-id="2586654605570" data-thing-id="39469217"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">admire</div></div><div class="col_b col text"><div class="text">(v) khâm phục, thán phục</div></div></div><div class="thing text-text"
            data-learnable-id="2586655654146" data-thing-id="39469233"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">admit</div></div><div class="col_b col text"><div class="text">(v) nhận vào, cho vào, kết hợp</div></div></div><div class="thing text-text"
            data-learnable-id="2586657161474" data-thing-id="39469256"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adopt</div></div><div class="col_b col text"><div class="text">(v) nhận làm con nuôi, bố mẹ nuôi</div></div></div><div class="thing text-text"
            data-learnable-id="2586661880066" data-thing-id="39469328"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adult</div></div><div class="col_b col text"><div class="text">(n) (adj) người lớn, người trưởng thành; trưởng thành</div></div></div><div class="thing text-text"
            data-learnable-id="2586670203138" data-thing-id="39469455"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advance</div></div><div class="col_b col text"><div class="text">(n) (v) sự tiến bộ, tiến lên; đưa lên, đề xuất</div></div></div><div class="thing text-text"
            data-learnable-id="2586671317250" data-thing-id="39469472"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advanced</div></div><div class="col_b col text"><div class="text">(adj) tiên tiến, tiến bộ, cấp cao</div></div></div><div class="thing text-text"
            data-learnable-id="2586675511554" data-thing-id="39469536"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">in advance of</div></div><div class="col_b col text"><div class="text">trước, sớm ( thời gian)</div></div></div><div class="thing text-text"
            data-learnable-id="2586677281026" data-thing-id="39469563"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advantage</div></div><div class="col_b col text"><div class="text">(n) sự thuận lợi, lợi ích, lợi thế</div></div></div><div class="thing text-text"
            data-learnable-id="2586680951042" data-thing-id="39469619"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advantage</div></div><div class="col_b col text"><div class="text">(n) sự thuận lợi, lợi ích, lợi thế</div></div></div><div class="thing text-text"
            data-learnable-id="2586701005058" data-thing-id="39469925"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">take advantage of</div></div><div class="col_b col text"><div class="text">lợi dụng</div></div></div><div class="thing text-text"
            data-learnable-id="2586707427586" data-thing-id="39470023"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">adventure</div></div><div class="col_b col text"><div class="text">(n) sự phiêu lưu, mạo hiểm</div></div></div><div class="thing text-text"
            data-learnable-id="2586709000450" data-thing-id="39470047"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advertise</div></div><div class="col_b col text"><div class="text">(v) báo cho biết, báo cho biết trước</div></div></div><div class="thing text-text"
            data-learnable-id="2586724270338" data-thing-id="39470280"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advertising</div></div><div class="col_b col text"><div class="text">(n) sự quảng cáo, nghề quảng cáo</div></div></div><div class="thing text-text"
            data-learnable-id="2586729120002" data-thing-id="39470354"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advertisement</div></div><div class="col_b col text"><div class="text">(n)  quảng cáo</div></div></div><div class="thing text-text"
            data-learnable-id="2586732724482" data-thing-id="39470409"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advice</div></div><div class="col_b col text"><div class="text">(n)  lời khuyên, lời chỉ bảo</div></div></div><div class="thing text-text"
            data-learnable-id="2586734690562" data-thing-id="39470439"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">advise</div></div><div class="col_b col text"><div class="text">(v) khuyên, khuyên bảo, răn bảo</div></div></div><div class="thing text-text"
            data-learnable-id="2586735870210" data-thing-id="39470457"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">affair</div></div><div class="col_b col text"><div class="text">(n) việc</div></div></div><div class="thing text-text"
            data-learnable-id="2586737377538" data-thing-id="39470480"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">affect</div></div><div class="col_b col text"><div class="text">(v) làm ảnh hưởng, tác động đến</div></div></div><div class="thing text-text"
            data-learnable-id="2586745504002" data-thing-id="39470604"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">affection</div></div><div class="col_b col text"><div class="text">(n) tình cảm, cảm xúc</div></div></div><div class="thing text-text"
            data-learnable-id="2586746749186" data-thing-id="39470623"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">afford</div></div><div class="col_b col text"><div class="text">(v)  có thể, có đủ khả năng, điều kiện (làm gì)</div></div></div><div class="thing text-text"
            data-learnable-id="2586748846338" data-thing-id="39470655"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">afraid</div></div><div class="col_b col text"><div class="text">(adj)  sợ, sợ hãi, hoảng sợ</div></div></div><div class="thing text-text"
            data-learnable-id="2586765689090" data-thing-id="39470912"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">after</div></div><div class="col_b col text"><div class="text">(prep) (conj) sau, đằng sau, sau khi</div></div></div><div class="thing text-text"
            data-learnable-id="2586768965890" data-thing-id="39470962"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">afternoon</div></div><div class="col_b col text"><div class="text">(n)  buổi chiều</div></div></div><div class="thing text-text"
            data-learnable-id="2586770604290" data-thing-id="39470987"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">afterwards</div></div><div class="col_b col text"><div class="text">(adv)  sau này, về sau, rồi thì, sau đấy</div></div></div><div class="thing text-text"
            data-learnable-id="2586778009858" data-thing-id="39471100"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">again</div></div><div class="col_b col text"><div class="text">(adv)  lại, nữa, lần nữa</div></div></div><div class="thing text-text"
            data-learnable-id="2586779582722" data-thing-id="39471124"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">against</div></div><div class="col_b col text"><div class="text">(prep) chống lại, phản đối</div></div></div><div class="thing text-text"
            data-learnable-id="2586780958978" data-thing-id="39471145"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">age</div></div><div class="col_b col text"><div class="text">(n)  tuổi</div></div></div><div class="thing text-text"
            data-learnable-id="2586782597378" data-thing-id="39471170"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">aged</div></div><div class="col_b col text"><div class="text">(adj) già đi</div></div></div><div class="thing text-text"
            data-learnable-id="2586789740802" data-thing-id="39471279"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">agency</div></div><div class="col_b col text"><div class="text">(n)  tác dụng, lực; môi giới, trung gian</div></div></div><div class="thing text-text"
            data-learnable-id="2586794131714" data-thing-id="39471346"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">agent</div></div><div class="col_b col text"><div class="text">(n) đại lý, tác nhân</div></div></div><div class="thing text-text"
            data-learnable-id="2586801996034" data-thing-id="39471466"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">aggressive</div></div><div class="col_b col text"><div class="text">(adj) xâm lược, hung hăng (US: xông xáo)</div></div></div><div class="thing text-text"
            data-learnable-id="2586805600514" data-thing-id="39471521"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">ago</div></div><div class="col_b col text"><div class="text">(adv)  trước đây</div></div></div><div class="thing text-text"
            data-learnable-id="2586810122498" data-thing-id="39471590"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">agree</div></div><div class="col_b col text"><div class="text">(v) đồng ý, tán thành</div></div></div><div class="thing text-text"
            data-learnable-id="2586811957506" data-thing-id="39471618"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">agreement</div></div><div class="col_b col text"><div class="text">(n) sự đồng ý, tán thành; hiệp định, hợp đồng</div></div></div><div class="thing text-text"
            data-learnable-id="2586817331458" data-thing-id="39471700"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">ahead</div></div><div class="col_b col text"><div class="text">(adv) trước, về phía trước</div></div></div><div class="thing text-text"
            data-learnable-id="2586820935938" data-thing-id="39471755"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">aid</div></div><div class="col_b col text"><div class="text">(n) (v)  sự giúp đỡ; thêm vào, phụ vào</div></div></div><div class="thing text-text"
            data-learnable-id="2586822443266" data-thing-id="39471778"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">aim</div></div><div class="col_b col text"><div class="text">(n) (v)  sự nhắm (bắn), mục tiêu, ý định; nhắm, tập trung, hướng vào</div></div></div><div class="thing text-text"
            data-learnable-id="2586825261314" data-thing-id="39471821"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">air</div></div><div class="col_b col text"><div class="text">(n)  không khí, bầu không khí, không gian</div></div></div><div class="thing text-text"
            data-learnable-id="2586828210434" data-thing-id="39471866"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">aircraft</div></div><div class="col_b col text"><div class="text">(n)  máy bay, tàu bay, khí cầu</div></div></div><div class="thing text-text"
            data-learnable-id="2586831356162" data-thing-id="39471914"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">airport</div></div><div class="col_b col text"><div class="text">(n)  sân bay, phi trường</div></div></div><div class="thing text-text"
            data-learnable-id="2586833387778" data-thing-id="39471945"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">alarm</div></div><div class="col_b col text"><div class="text">(n) (v)  báo động, báo nguy</div></div></div><div class="thing text-text"
            data-learnable-id="2586835878146" data-thing-id="39471983"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">alarming</div></div><div class="col_b col text"><div class="text">(adj) làm lo sợ, làm hốt hoảng, làm sợ hãi</div></div></div><div class="thing text-text"
            data-learnable-id="2586854752514" data-thing-id="39472271"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">alarmed</div></div><div class="col_b col text"><div class="text">(adj)  báo động</div></div></div><div class="thing text-text"
            data-learnable-id="2586858815746" data-thing-id="39472333"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">alcohol</div></div><div class="col_b col text"><div class="text">(n) rừợu cồn</div></div></div><div class="thing text-text"
            data-learnable-id="2586873430274" data-thing-id="39472556"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">alcoholic</div></div><div class="col_b col text"><div class="text">(adj) (n) rượu, người nghiện rượu</div></div></div><div class="thing text-text"
            data-learnable-id="2586879787266" data-thing-id="39472653"><div class="thinguser"><i class="ico ico-seed ico-purple"></i></div><div class="ignore-ui pull-right"><input type="checkbox" ></div><div class="col_a col text"><div class="text">alive</div></div><div class="col_b col text"><div class="text">(adj) sống, vẫn còn sống, còn tồn tại</div></div></div><div class="things-footer things-row clearfix"><a class="ignore-save ignore-ui btn pull-right btn-primary btn-large btn-block hide">
            Lưu
        </a></div></div>

    </div>


            </div>
        </div>

@endsectinon()